# Generated by Django 5.2 on 2025-04-20 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_attendance_date_attendance_is_in_location_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attendance",
            name="date",
        ),
        migrations.RemoveField(
            model_name="attendance",
            name="is_in_location",
        ),
        migrations.RemoveField(
            model_name="attendance",
            name="time",
        ),
        migrations.AlterField(
            model_name="weekday",
            name="day",
            field=models.CharField(
                choices=[
                    ("MON", "Thứ 2"),
                    ("TUE", "Thứ 3"),
                    ("WED", "Thứ 4"),
                    ("THU", "Thứ 5"),
                    ("FRI", "Thứ 6"),
                    ("SAT", "Thứ 7"),
                    ("SUN", "Chủ nhật"),
                ],
                max_length=3,
                unique=True,
            ),
        ),
    ]
