# Generated by Django 5.2 on 2025-04-20 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_remove_attendance_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="is_in_location",
            field=models.BooleanField(default=True),
        ),
    ]
