# Generated by Django 5.2 on 2025-04-20 13:43

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_user_address_user_avatar_user_bio_user_date_joined_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="avatars/",
                validators=[core.models.validate_avatar_file],
                verbose_name="Ảnh đại diện",
            ),
        ),
    ]
